apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kube-prometheus-stack
namespace: monitoring
# Using patches instead of patchesStrategicMerge as per current Kustomize standards
# Add cluster-specific patches if needed
# patches:
#  - path: patches/prometheus-values.yaml
#    target:
#      kind: ConfigMap
#      name: prometheus-values
