apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base/traefik
  - depends-on-cilium.yaml
patches:
  - path: patches/traefik-values.yaml
    target:
      kind: HelmRelease
      name: traefik
