# Cluster-specific overrides for Cilium configuration
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    # Kalimdor cluster-specific Cilium configuration
    # These values will override the base configuration
    
    # 1. Core configuration for Talos with kube-proxy replacement
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "7445"
    
    # 2. Cilium version for this specific cluster
    image:
      repository: quay.io/cilium/cilium
      tag: v1.17.2
    
    # 3. Network device configuration
    # Auto-detect network interfaces instead of hardcoding names
    devices: ""
    
    # 4. Routing configuration
    routingMode: "native"
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: "10.0.0.0/8"
    
    # 5. Load balancer configuration
    loadBalancer:
      algorithm: "maglev"
      mode: "dsr"
    
    # 6. Network masquerading (required for GitHub connectivity)
    bpf:
      masquerade: true
    
    # 7. DNS configuration (critical for external domain resolution)
    dns:
      enabled: true
      enableNodePort: true
    
    # 8. Host-to-pod communication
    hostServices:
      enabled: true
      protocols: tcp
    
    # 9. External connectivity options
    externalIPs:
      enabled: true
    hostPort:
      enabled: true
    nodePort:
      enabled: true
      strictMode: false
    
    # 10. Additional connectivity features
    ipv4:
      enabled: true
    enableXTSocketFallback: true
    
    # 11. Monitoring and observability
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    
    # 12. Gateway API support
    gatewayAPI:
      enabled: true
    
    # 13. Cgroup and BPF filesystem mounts (required for Talos)
    cgroup:
      hostRoot: "/sys/fs/cgroup"
    
    # 14. Performance optimizations
    sockops:
      enabled: true
