# Cluster-specific overrides for Cilium configuration
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    # Kalimdor cluster-specific Cilium configuration
    # These values will override the base configuration
    
    # Ensure kubeProxyReplacement is enabled for this cluster
    kubeProxyReplacement: true
    
    # Cilium version for this specific cluster
    image:
      repository: quay.io/cilium/cilium
      tag: v1.17.2
    
    # Allow Cilium to auto-detect network devices
    # This is more portable across different node configurations
    devices: ""
    
    # Routing configuration for Kalimdor
    routingMode: "native"
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: "10.0.0.0/8"
    
    # Load balancer configuration for Kalimdor
    loadBalancer:
      algorithm: "maglev"
      mode: "dsr"
      
    # Network masquerading
    bpf:
      masquerade: true
    
    # Advanced connectivity settings for GitHub access
    dns:
      enabled: true
    
    hostServices:
      enabled: true
      protocols: tcp
    
    hostPort:
      enabled: true
    
    nodePort:
      enabled: true
      strictMode: false
      
    gatewayAPI:
      enabled: true
    
    # Explicitly allow outbound traffic to GitHub
    ipv4:
      enabled: true
    enableXTSocketFallback: true
    
    # Kubernetes API endpoint configuration for Talos
    k8sServiceHost: "localhost"
    k8sServicePort: "7445"
    
    # Auto-mount the necessary mounts (important for BPF functionality)
    cgroup:
      hostRoot: "/sys/fs/cgroup"
      
    # Performance optimizations
    sockops:
      enabled: true
