apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/kalimdor
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-cluster-repo
  dependsOn:
    - name: flux-system
  # Temporarily commented out for debugging
  # postBuild:
  #   substituteFrom:
  #     - kind: ConfigMap
  #       name: cluster-settings
  #     - kind: Secret
  #       name: cluster-secrets
