apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  values:
    # Kalimdor cluster-specific Traefik configuration
    # These values will override the base configuration
    
    # Configure for Cilium integration
    # This works with your Cilium v1.16.8 setup
    providers:
      kubernetesCRD:
        enabled: true
        namespaces: []
        ingressClass: traefik
      kubernetesIngress:
        enabled: true
        namespaces: []
        ingressClass: traefik
    
    # Additional security settings
    additionalArguments:
      - "--api.insecure=false"
      - "--accesslog=true"
      - "--log.level=INFO"
      
    # Resources configuration
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
    
    # Service configuration with manual IP assignment
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        # Manually assign specific IP for Cilium L2 announcements
        io.cilium/lb-ipam-ips: "10.0.20.1"  # Replace with your desired Traefik IP
      # Optional: Use this if you want to mark the service for L2 announcement policy
      labels:
        announce-l2: "true"
