apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  # Add other base infrastructure components as they're configured
  # - cert-manager
  # - cloudflared
  # - external-dns
  # - headscale
