apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repository.yaml
  - helm-release.yaml
  - cilium-values.yaml
  - l2-announcement-policy.yaml
  # Network policy examples are included but commented out by default
  # Uncomment when you're ready to apply them
  # - network-policy-examples.yaml
