apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
  namespace: kube-system
spec:
  # Select all services with type LoadBalancer by default
  # Services must have loadBalancerClass unspecified or set to io.cilium/l2-announcer
  serviceSelector: {}
  
  # Select nodes that should announce the services
  # By default, all nodes are selected, but you can restrict this to specific nodes
  # For example, to exclude control plane nodes:
  # nodeSelector:
  #   matchExpressions:
  #     - key: node-role.kubernetes.io/control-plane
  #       operator: DoesNotExist
  
  # Specify which network interfaces should be used for announcements
  # If not specified, all interfaces will be used
  interfaces:
  - ^eth[0-9]+
  
  # Enable announcement of external IPs
  externalIPs: true
  
  # Enable announcement of load balancer IPs
  loadBalancerIPs: true
