apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: "35.0.0"  # Using a stable version
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: values.yaml
