apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-values
  namespace: kube-system
data:
  values.yaml: |
    # Default Traefik configuration values
    deployment:
      replicas: 2
    
    # Enable the dashboard
    ingressRoute:
      dashboard:
        enabled: true
    
    # Configure ports
    ports:
      web:
        port: 8000
        exposedPort: 80
        expose: {}
        protocol: TCP
      websecure:
        port: 8443
        exposedPort: 443
        expose: {}
        protocol: TCP
    
    # Configure providers
    providers:
      kubernetesCRD:
        enabled: true
        namespaces: []
      kubernetesIngress:
        enabled: true
        namespaces: []
    
    # Configure service
    service:
      enabled: true
      type: LoadBalancer
      # Use Cilium L2 announcer LoadBalancer class
      loadBalancerClass: "io.cilium/l2-announcer"
      annotations:
        # Cilium LoadBalancer IP annotation for L2 announcements
        lbipam.cilium.io/ips: "10.0.20.1"
    
    # Configure logs
    logs:
      general:
        level: INFO
      access:
        enabled: true
