apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base/cilium
  - l2-announce-policy.yaml
patches:
  - path: patches/cilium-values.yaml
    target:
      kind: HelmRelease
      name: cilium
