---
# L2 Announcement Policy for manual IP assignment strategy
# This policy enables Layer 2 announcements for manually assigned IPs in services
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: kalimdor-service-announcements
  namespace: kube-system
spec:
  # Service Selector - uncomment to only announce services with specific labels
  # This enables explicit control over which services get announced,
  # perfect for manual IP management
  # serviceSelector:
  #   matchLabels:
  #     announce-l2: "true"
  
  # Node Selection Strategy
  # Only worker nodes will announce IPs - prevents control plane from
  # handling external traffic
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  
  # Network interfaces to use for ARP announcements
  # Specify exactly which interfaces should handle the ARP responses
  # This ensures your manual IPs are only announced on the intended networks
  interfaces:
    - "eth[0-9]+"  # Matches eth0, eth1, etc.
  
  # IP Types to announce
  # Both are enabled to support maximum flexibility in how you assign IPs:
  # - externalIPs: Use when adding IPs via service.spec.externalIPs array
  # - loadBalancerIPs: Use when adding IPs via service.status.loadBalancer.ingress
  #   or the io.cilium/lb-ipam-ips annotation
  externalIPs: true
  loadBalancerIPs: true
