---
# LoadBalancer IP Pool for Cilium
# This defines the available IPs that can be assigned to LoadBalancer services
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: kalimdor-lb-pool
spec:
  # Define the IP range for LoadBalancer services
  cidrs:
  - cidr: "10.0.20.0/24"
    
  # Optional: Reserve specific IPs that should not be assigned
  # Useful for network equipment, gateways, etc.
  # externalIPs:
  # - "10.0.20.254"
    
  # Service selector - which services can use this pool
  # Empty means all services can use it
  serviceSelector:
    matchExpressions: []
    
  # Disable the pool if needed (set to false)
  disabled: false
