apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: metrics-server
      version: "3.12.2"  # Using a stable version
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: metrics-server-values
      valuesKey: values.yaml
